.travis.yml
poli/controllers/idaactions.py
poli/models/idaactions.py
poli/views/apiview.py
tests/api_tests.py

This PR is intented to add support for IDA structure creation and update

Managing IDA structures

---

config.py
poli/controllers/analysis.py
poli/controllers/family.py
poli/controllers/idaactions.py
poli/controllers/sample.py
poli/controllers/user.py
poli/models/family.py
poli/models/models.py
poli/models/user.py
poli/views/apiview.py
skelenox.py
tests/api_tests.py

Fix cleaning

---

.travis.yml
requirements.txt

Removing useless deps

---

.travis.yml

* Removing the test coverage of the virtualenv

Removing the coverage of virtualenv (#58)

---

docs/API.md
poli/controllers/sample.py
poli/models/idaactions.py
poli/models/sample.py
poli/views/apiview.py
tests/tests_api.py

However, the indexes are not created during a schema migration,
if you are updating an existing database, you might need to create them by hand.

Speed up comments and name search with indexes

---

docs/TODO.md
poli/controllers/idaactions.py
poli/controllers/tasks/task_analyzeitrb.py
poli/models/sample.py
poli/views/apiview.py
poli/views/webui.py
skelenox.py

This PR add several features and bugfixes:
* BUGFIX The function names from `AnalyzeIt.rb` were parsed with a trailing `\n`
* FEAT The update are pulled in Skelenox in a different thread, so now the UI won't hang during an update
* FEAT If the sample is not found on the server, it is automatically uploaded
* REFACTO The skelenox architecture has been refactored around a main class `SkelCore` wich is better suitable for a use as a plugin (for example)

Add threading to skelenox

---

poli/controllers/idaactions.py
poli/models/idaactions.py
poli/views/apiview.py
tests/tests_api.py

IDA type definitions are now handled.
As a bonus, API tests have been refactored

IDA Types management

---

poli/controllers/api.py
poli/views/apiview.py
poli/views/forms.py
poli/views/webui.py
tests/tests_api.py
tests/tests_webui.py

The user can now upload several files using the upload form at the index page.
A bug was also corrected in the api tests, as the sample upload was done via the webui instead of the upload endpoint.

Implement the multiple sample upload

---

poli/controllers/api.py
poli/views/webui.py

This should solve issue #20 by adding a simple flash when failing to create a Yara

Add some feedback when creating a yara

---

poli/controllers/sample.py
tests/example_pe.machex
tests/tests_webui.py

Cleanup & Tests

---

poli/controllers/api.py
poli/controllers/sample.py
poli/views/apiview.py
poli/views/webui.py
tests/tests_api.py

This fixes #97 , a user can now upload a zip containing several samples.

Fix Zip archive upload

---

poli/controllers/user.py
tests/tests_webui.py

A user can now change a user password.
This is the same commit as #94, with an added test.
Thanks to @harfangeek

Fix userpassword

---

.travis.yml
poli/views/apiview.py

This includes an osx travis build target and a fix for #106 .

Mac osX compatibility

---

docs/TODO.md
poli/views/apiview.py
poli/views/webui.py
skelenox.py

This commit enables an initial synchronization when launching skelenox.
It also removes unused configuration options, and add a new one wich modify the synchronization delay

Initial names and comments synchronization

---

docs/TODO.md
poli/controllers/sample.py
poli/templates/sample.html
poli/views/apiview.py
poli/views/webui.py
skelenox.py
tests/tests_api.py

* Capability to get proposed names in IDA from machoc hashes

Machoc name imports

---

.travis.yml
docs/TODO.md
poli/controllers/api.py
poli/controllers/sample.py
poli/templates/diff.html
poli/views/apiview.py
poli/views/webui.py
skelenox.py
tests/tests_webui.py

*  Optimize machoc diffing
* Refactor some elements to remove useless code

Refactoring

---

poli/controllers/analysis.py
poli/controllers/api.py
poli/controllers/family.py
poli/controllers/idaactions.py
poli/controllers/jobpool.py
poli/controllers/task.py
poli/controllers/tasks/task_analyzeitrb.py
poli/controllers/tasks/task_peinfo.py
poli/controllers/tasks/task_strings.py
poli/controllers/tasks/task_yara.py
poli/controllers/user.py
poli/controllers/yara_rule.py
poli/models/analysis.py
poli/models/family.py
poli/models/idaactions.py
poli/models/models.py
poli/models/sample.py
poli/models/user.py
poli/models/yara_rule.py
poli/templates/index.html
poli/templates/main.html
poli/templates/settings.html
poli/views/apiview.py
poli/views/forms.py
poli/views/webui.py
skelenox.py
tests/tests_api.py
tests/tests_webui.py

* New structure and structure members are created.
* Structures and members can be renamed

Skelenox structure management

---

poli/controllers/sample.py

all samples where equal due to commit 8d923ba1da46f8ae32abd2bd85c578cd97b33a8b

Fix machoc diffing 

---

analysis_tools/AnalyzeIt.rb

Fix AnalyzeIt typo

---

skelenox.py

This should fix #148.
It also implements a patch for #136, which could be improved when adding IDA 7.0 compatibility

Remove a previous instance if found
